#! /bin/sh
set -e

./jack run build
./jack build

today=$(date +%s)

echo "backup jack-binary to .olds/$today"
mkdir -p .olds/$today
cp -r jack-binary/* .olds/$today/

echo "Copying to jack-binary directory"
rm -rf jack-binary
mkdir -p jack-binary/libs

cp -f out/jars/jack.jar jack-binary/
cp -fr out/libs jack-binary/