/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.7/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    implementation("org.tomlj", "tomlj", "1.1.1")
    implementation("org.cyclonedx", "cyclonedx-core-java", "9.0.1")
    implementation("org.apache.maven.resolver" , "maven-resolver-supplier", "1.9.20")
    implementation("org.apache.maven", "maven-resolver-provider", "3.9.7")
    implementation("org.slf4j", "slf4j-api", "2.0.9")

    implementation("org.slf4j", "slf4j-simple", "2.0.6")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    // Define the main class for the application.
    mainClass = "io.github.goldmensch.Jack"
}
