#! /bin/sh
set -e

./jack run build
./jack build ${@:1}

today=$(date +%s)

echo "backup jack-binary to .olds/$today"
mkdir -p .olds/$today
cp -r jack-binary/* .olds/$today/

echo "Copying to jack-binary directory"
rm -rf jack-binary/*
mkdir -p jack-binary

cp -fr out/distributions/* jack-binary/