#! /bin/sh

classpath=".jack/jack.jar:.jack/libs/antlr4-runtime-4.11.1.jar:.jack/libs/checker-qual-3.21.2.jar:.jack/libs/plexus-utils-3.5.1.jar:.jack/libs/tomlj-1.1.1.jar"
java -cp $classpath io.github.goldmensch.Jack $1