[project]
name = "jack"
version = "0.1"
author = "Nick Hensel"

[repositories]
mavenCentral = true

[dependencies]
"org.tomlj:tomlj" = "1.1.1"

"org.apache.maven:maven-model" = "3.9.6"
"org.apache.maven:maven-resolver-provider" = "3.9.6"
"org.apache.maven.resolver:maven-resolver-supplier" = "1.9.20"
"org.slf4j:slf4j-simple" = "1.7.36"
[manifest]
main = "io.github.goldmensch.Jack"