[project]
name = "jack"
version = "0.1"
author = "Nick Hensel"

[dependencies]
"org.tomlj:tomlj" = "1.1.1"
"org.apache.maven:maven-model" = "3.9.6"
"org.apache.maven.resolver:maven-resolver-api" = "1.9.20"
[manifest]
main = "io.github.goldmensch.Jack"